cuatiemthanhnhung/WebAdmin/Controllers/BlogDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using SharedObjects;

using SharedObject.ViewModels;
using SharedObject.Extentions;
using SharedObject.Commons;

namespace WebAdmin.Controllers
{
    public class BlogDetailController : Controller
    {

        private readonly IBlogDetailService _BlogDetailService;
        private readonly IBlogService blogService;

        public BlogDetailController(IBlogDetailService BlogDetailService, IBlogService blogService)
        {
            _BlogDetailService = BlogDetailService;
            this.blogService = blogService;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> BlogDetail(string id)
        {
            var result = await _BlogDetailService.GetByBlogId(id);
            ViewBag.Blog = (await blogService.GetById(id));
            return View(result);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult EditBlogDetail(string blogDetailId, string blogId)
        {
            ViewBag.BlogId = blogId;
            if (string.IsNullOrEmpty(blogDetailId))
            {
                ViewBag.BlogDetailId = "";
            }
            else
            {
                ViewBag.BlogDetailId = blogDetailId;
            }
            
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Save([FromBody] BlogDetailViewModel model)
        {
            string token = User.GetSpecificClaim("token");
            ResponseResult result = new ResponseResult();
            if (string.IsNullOrEmpty(model.BlogDetailId))
            {
                result = await _BlogDetailService.Add(model, token);
                if (result.StatusCode == 200)
                {
                    return Json(new { statusCode = 1 });

                }
                else
                {
                    return Json(new { statusCode = 0 });
                }
               
            }
            else
            {
                result = await _BlogDetailService.Update(model, token);
                if (result.StatusCode == 200)
                {
                    return Json(new { statusCode = 2 });

                }
                else
                {
                    return Json(new { statusCode = 0 });
                }


            }

        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<JsonResult> Delete(string id)
        {

            string token = User.GetSpecificClaim("token");
            var result = await _BlogDetailService.Delete(id, token);
            return Json(new { statusCode = result.StatusCode });

        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<JsonResult> GetById(string id)
        {
            var cate = await _BlogDetailService.GetById(id);
            return Json(new { result = cate });
        }

       
    }
}

cuatiemthanhnhung/WebAdmin/Views/BlogDetail/BlogDetail.cshtml
@using SharedObjects

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var blog = (SharedObject.ValueObjects.VBlog)ViewBag.Blog;
}
@model IEnumerable<SharedObject.ValueObjects.VBlogDetail>

<div class="container">
    <div class="row">
        <div class="col-md-12">

            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light">
                <div class="portlet-title">

                    <div class="caption col-md-12">
                        <span class="caption-subject font-green-sharp bold uppercase">
                            Quản lý chi tiết bài viết: @blog.Tittle
                        </span>
                    </div>

                    <div class="portlet-body">

                        <div class="table-toolbar">

                            <div class="col-md-2 col-sm-12 col-xs-12 pull-left">
                                <a class="btn btn-success" href="@Url.Action("EditBlogDetail","BlogDetail", new {blogId =""+ blog.BlogId })" data-toggle="modal" id="btn-add">Tạo mới</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="table-responsive col-md-12">
                    <table class="table table-bordered table-hover table-striped table-responsive">
                        <thead>
                            <tr class="text-center">

                                <td>Ngày tạo</td>
                                <td>Số thứ tự</td>
                                <td>Tiêu đề</td>
                                <td>Tác vụ</td>

                            </tr>
                        </thead>
                        <tbody id="table-courseCategory">
                            @foreach (var item in Model)
                            {
                                <tr id="tr-@item.BlogDetailId" class="text-center">

                                    <td>
                                        @{ string dateDisplay = DateTimeService.FormatDateTime((DateTime)item.DateCreated); }
                                        @dateDisplay
                                    </td>
                                    <td> @item.Number</td>

                                    <td> @item.Tittle</td>

                                    <td class="text-center">
                                        <a title="Cập nhật" class="btn default btn-xs green update" href="@Url.Action("EditBlogDetail","BlogDetail", new {blogDetailId = item.BlogDetailId, blogId = item.BlogId })">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </a>

                                        <a title="Xóa" class="btn default btn-xs red delete" data-id="@item.BlogDetailId"><span class="glyphicon glyphicon-trash"></span></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="pagination" id="pagination">
                </div>
            </div>

        </div>

    </div>

</div>

@section Script{
  
    <script src="~/js/BlogDetail.js"></script>
}

cuatiemthanhnhung/WebAdmin/Views/BlogDetail/EditBlogDetail.cshtml
@{
    ViewData["Title"] = "EditBlogDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <div class="row">

        <div class="col-md-12">

            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light" style="min-height:900px">
                <div class="portlet-title">

                    <div class="caption col-md-12">
                        <span class="caption-subject font-green-sharp bold uppercase">
                            Cập nhật chi tiết bài viết
                        </span>
                    </div>

                    <div class="portlet-body">
                        <div class="table-toolbar">

                            <div class="col-md-3 col-sm-12 col-xs-12">

                                <div class="btn-group" role="group" aria-label="Basic example">

                                    <button id="btn-save" type="button" class="btn btn-success">Lưu</button>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    <form id="frm-save">

                        @*hidden id*@
                        <p hidden id="hid-blogId">@ViewBag.blogId</p>
                        <p hidden id="hid-blogDetailId">@ViewBag.blogDetailId</p>

                        <div class="form-group col-md-6 col-xs-12">
                            <label for="txt-Number">Số thứ tự đoạn văn trong bài viêt </label>
                            <input type="number" min="1" class="form-control" id="txt-Number" name="Number">
                        </div>
                        <div class="form-group col-md-6 col-xs-12">
                            <label for="txt-Tittle">Tiêu đề </label>
                            <input type="text" class="form-control" id="txt-Tittle" name="Tittle">
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="txt-Content">Viết nội dung</label>
                                <textarea id="txt-Content" name="Content"></textarea>

                            </div>
                        </div>


                    </form>


                </div>

            </div>

        </div>

    </div>
</div>
@section Script{
    <script src="~/lib/ckeditor/ckeditor.js"></script>
    <script src="~/js/EditBlogDetail.js"></script>
}